openapi: 3.0.0
info:
  version: 'v1'
  title: 'A simple API introduction '
schemes:
  http
  https
  
paths:
  /todos/{id}:
    get:
      x-operation-name: findTodoById
      tags:
        - Todos
      responses:
        '200':
          description: Todo model instance
          content:
            application/json:
              schema:
                $ref: '#/models/todo'
      parameters:
        - name: id
          in: path
          schema:
            type: number
          required: true
        - name: items
          in: query
          schema:
            type: boolean
  /todos:
    post:
      x-operation-name: createTodo
      tags:
        - Todos
      responses:
        '201':
          description: todos created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing todos already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/models/todo'
    get:
      x-operation-name: findTodos
      tags:
        - Todos
      responses:
        '200':
          description: Array of Todo model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/models/todo'
        '400':
          description: bad input parameter
      parameters:
        - name: filter
          in: query
          style: deepObject
          explode: true
          schema:
            properties:
              where:
                type: object
              fields:
                type: object
              offset:
                type: integer
                minimum: 0

servers:
  - url: 'http://api.kudobuzz.com'

models:
  todo:
    title: Todo
    properties:
      id:
        type: number
      title:
        type: string
    