openapi: 3.0.0

info:
  version: 1.0.0
  title: 'health check '
  description: 'A simple health check for the boilerplate'


path:
todos/health:
    'get':
      summary: checks that the api is working 
      description: asserts that the api is working as exp
      responses:
        '200':
          description: the health check is passed
          examples:
            application/json:
             {
                "status": "Service available",
                "timestamp": "2018-01-17T03:36:48Z"
                "database": "connection ok"
                  
             }
                  
        '503':
          description: 'health check failed '
          examples:
            application/json:
              {
                "status": "Service Unavailable",
                "errors": {
                  "database": "connection refused"
                  }
                }

host: localhost
basePath: /api/v1